### ISSUE TITLE
QUESTION: Converting units within input.py

### ISSUE THREAD

**Issue by Joshua-Shaffer** [nasa/trick#1019]
Is there a correct way to convert units using trick modules from an input.py script? I was attempting to convert using:
`temp = trick.UnitsConvFn_t`
`trick.sim_services.conv_fn_s("mg","m/s^2",temp)`
`valNew = trick.sim_services.convert_units(2.0, temp)`

but I receive the following error:
`trick.sim_services.conv_fn_s("mg","m/s2",temp)`
`TypeError: in method 'conv_fn_s', argument 3 of type 'UnitsConvFn_t *'`
which occurs since `temp` is a class instance of `UnitsConvFn_t`.

It's unclear if there's a separate module for converting units using python (trick_source/trick_swig/swig_convert_units.cpp appears to contain separate functions, but they're not exposed in any python modules).

I'm using Trick-17.5.1

**Comment by miltondean** [comment]
Trick is using UDUNITS2 to convert units in trick 17.4 and later.  It does a great job if you have supplied a c++ class parameter with a smart comment with a valid unit <trick_variable_name>.   You can use your input.py to set those values with different units by using :  
<trick_variable_name>=trick.attach_units("m/s2", 2.0).  
If you want to be able to have python perform the conversion, cfunits 3.2.9 (https://pypi.org/project/cfunits/) installs UDUNITS2 so that python can use the conversions.
