### ISSUE TITLE
Fatal Python error: Py_Initialize: unable to load the file system codec

### ISSUE THREAD

**Issue by WillFife** [nasa/trick#1177]
Hello. I have built Trick with python3.6 by pointing the configure script to a local anaconda environment python root directory
./configure --with-python=/Users/williamfife/opt/anaconda3/envs/TRICK/bin

The configure script ran nicely and I was able to build Trick

I also build a simulation and tried running it and the output seemed to not like Python

Is this something y'all have seen? Hoping it's something I can simply reconfigure

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010fa94e00 (most recent call first):
Process terminated by signal SIGABRT

**Comment by spfennell** [comment]
I don't recognize that specific error, but trick requires a python installation that includes a python-config binary. Is there a 'python-config' in your python bin? I remember there being problems with anaconda python envs in the past because of this. Trick's configuration is setup to use python-config to determine the paths to the python libraries. 

If you can, I recommend using system installs of python will make this a less painful thing to debug. 

If this is the problem, you may need to go in to /trick/share/ trick/makefiles/config_user.mk and edit the PYTHON_INCLUDES and PYTHON_LIB variables manually.
PYTHON_INCLUDES should have '-I' flags that point to your /include/python3.6 directory with header files. if -I<path> doesn't work, try -isystem<path> instead. I think we use -isystem, but I can't remember why off the top of my head.

PYTHON_LIB should have -L<path to python C libs> and -lpython3.6 or something like that (for linux).

 You can do this after running ./configure. Rerunning ./configure will overwrite any manual changes you have made.

**Comment by WillFife** [comment]
Will I need to run make after rerunning ./configure ?

**Comment by WillFife** [comment]
Is there a way I can point the ./configure script to look at an exact python binary and python-config binary?

in a /bin folder in my anaconda environment, I have multiple python binaries. See this output:

`ls ~/opt/anaconda3/envs/TRICK/bin/
2to3                    lzcat                   lzmainfo                python                  reset                   tset                    xzdec
2to3-3.6                lzcmp                   lzmore                  python3                 sqlite3                 unlzma                  xzdiff
c_rehash                lzdiff                  ncursesw6-config        python3-config          sqlite3_analyzer        unxz                    xzegrep
captoinfo               lzegrep                 openssl                 python3.6               tabs                    wheel                   xzfgrep
clear                   lzfgrep                 pip                     python3.6-config        tclsh                   wish                    xzgrep
idle3                   lzgrep                  pip3                    python3.6m              tclsh8.6                wish8.6                 xzless
idle3.6                 lzless                  pydoc                   python3.6m-config       tic                     xz                      xzmore
infocmp                 lzma                    pydoc3                  pyvenv                  toe                     xzcat
infotocap               lzmadec                 pydoc3.6                pyvenv-3.6`

**Comment by WillFife** [comment]
I resolved the original error with your help, thank you!

Now I am having an error accessing the Sim Objects created in the S_define in python.

I can access trick after "import trick" , but I cannot access the other objects?
