### ISSUE TITLE
Trick View: Java Lost Connection when running Trick tutorial

### ISSUE THREAD

**Issue by frewdr** [nasa/trick#1207]
System: MacBook Pro 2019, MacOS Montery 12.0.1, Trick Simulation release 19.3.0.

Running step 8 of the trick tutorial (https://nasa.github.io/trick/tutorial/ATutTrickView), Viewing Real Time Data with Trick View.

Receive the following error at the end of the real-time simulation. The simulation appears to complete without issue, so it might just be an annoyance.

Lost Connection
java.util.concurrent.ExecutionException: java.io.IOException: Reached end of stream.

Clicking "OK" closes the window and Trick View is available again.

**Comment by dbankieris** [comment]
That is the expected behavior when Trick View loses connection with a simulation, which occurs when a simulation terminates. If you prefer a different response, other options are available in Trick View under File -> Settings -> On Disconnect.
<img width="106" alt="image" src="https://user-images.githubusercontent.com/11414053/144637594-6f982238-4de9-4fdb-98ba-724b9273ebf1.png">
