### ISSUE TITLE
Cannot debug a Trick sim on Mac

### ISSUE THREAD

**Issue by ezcrues** [nasa/trick#1212]
I cannot debug a Trick simulation under Mac OS 11.  Here's what I get when I try to run SIM_ball_L1 in lldb:

EZBookPro16|SIM_ball_L1[88]> lldb S_main_Darwin_20.exe 
(lldb) target create "S_main_Darwin_20.exe"
Current executable set to '/Users/ezcrues/Trick/trick_dev/21.dev/trick_sims/Ball/SIM_ball_L1/S_main_Darwin_20.exe' (x86_64).
(lldb) run RUN_test/input.py 
error: shell expansion failed (reason: invalid JSON). consider launching with 'process launch'.
(lldb)

**Comment by ezcrues** [comment]
I do get the following:

mobius|SIM_ball_L1[36]> /usr/local/Cellar/llvm@11/11.1.0_3/bin/lldb-argdumper RUN_test/input.py
{"arguments":["RUN_test/input.py"]}
mobius|SIM_ball_L1[37]>

**Comment by ezcrues** [comment]
I can run the debugger if I use the 'process launch' command:

mobius|SIM_ball_L1[37]> lldb S_main_Darwin_20.exe 
(lldb) target create "S_main_Darwin_20.exe"
Current executable set to '/Users/ezcrues/Trick/trick_dev/21.dev/trick_sims/Ball/SIM_ball_L1/S_main_Darwin_20.exe' (x86_64).
(lldb) run RUN_test/input.py 
error: shell expansion failed (reason: invalid JSON). consider launching with 'process launch'.
(lldb) process launch RUN_test/input.py
Process 45793 launched: '/Users/ezcrues/Trick/trick_dev/21.dev/trick_sims/Ball/SIM_ball_L1/S_main_Darwin_20.exe' (x86_64)
|L   0|2022/01/12,09:34:09|mobius.jsc.nasa.gov| |T 0|0.000000| time =     0.00 , position =     5.000000 ,     5.000000

**Comment by alexlin0** [comment]
Which version of lldb are you running?  I'm on Big Sur and this is my version.

```bash
> lldb --version
lldb-1200.0.44.2
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
```

**Comment by ezcrues** [comment]
mobius|prti1516e_v5.5.3[24]> lldb --version
lldb-1300.0.42.3
Swift version 5.5.2-dev
mobius|prti1516e_v5.5.3[25]>

**Comment by ezcrues** [comment]
I'm concerned that we are getting strange behavior in our simulation with the mix of the Apple LLVM and the brew LLVM that we have backdated to llvm@11.

**Comment by ezcrues** [comment]
Is there any work being done to support brew LLVM at the current 13 level?

**Comment by spfennell** [comment]
@ezcrues I have been trying to fix this issue with llvm13 for months. There is an issue with the clang preprocessor that is instantiated in ICG. Unfortunately when llvm is built from source with debug info, the bug magically goes away, so I have not been able to drill deeper. 

I will prioritize this issue.

**Comment by ezcrues** [comment]
@spfennell : Thanks.  Let us know if there is something that we can do to help.  Something strange has happened with the latest Xcode update (13.2.1).  Our TrickHLA simulation will no longer run on the Mac.  We've looked into a number of different possible causes and have eliminated everything but Trick, the Pitch RTI, and LLVM@11.  It's clearly a nasty memory corruption issue but I cannot track it down.

**Comment by spfennell** [comment]
@ezcrues 
I have confirmed that building llvm 13 from source with mostly default settings does not have the same issues as brew's version, although I do get some other interesting warnings. The brew formulae commit history for llvm has been very active in the last few versions of llvm, so I will try to isolate which settings are causing the problems. This includes changing xcode toolchain settings, so you may be on to something with the xcode update that you mentioned. You can see the settings they use with their version of llvm here:

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/llvm.rb

You might try building llvm 13 and see if it solves any of your issues with the TrickHLA sim. Below are the shell commands with configuration options I used. I went ahead and added lldb to the build as well.

instructions here:
https://llvm.org/docs/GettingStarted.html

```
brew install ninja
git clone https://github.com/llvm/llvm-project.git ${HOME}/llvm-project
cd ${HOME}/llvm-project
git checkout llvmorg-13.0.0
mkdir build
cd build
cmake -GNinja -DLLVM_ENABLE_PROJECTS="clang;lldb" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=${HOME}/llvm -DLLDB_INCLUDE_TESTS=OFF ../llvm
ninja
ninja install
```

I will continue to isolate where the problem is either with trick or with brew's configuration.

**Comment by spfennell** [comment]
@ezcrues Now that the llvm versions are congruent do you still have this problem?
