### ISSUE TITLE
Need preCP hook for S_overrides.mk to support actions early in build, without Makefile_sim consequences

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#136]
Currently, if you want to hook in an action early in the build process (before ICG) you can hook to Makefile_sim in this way in your S_overrides.mk:

```
 Makefile_sim : my_prerequisite_goes_here
```
This works for the most part, but has a nasty consequence such that any actions taken by "my_prerequisite_goes_here" get triggered for ANY make command.  Including 'make spotless'.  Since my action generates some code and takes 5 minutes, this solution won't work for me.

I have a workaround I'd like you guys to evaluate/absorb:

${TRICK_HOME}/makefiles/Makefile.sim changes:
```
all : ${TRICK_HOME}/lib_${TRICK_HOST_CPU}/libtrick.a preMakefile_simHook Makefile_sim
    @/bin/cp ${TRICK_HOME}/bin/MAKE_out_header.txt MAKE_out
    @$(MAKE) --no-print-directory -f Makefile_sim all 2>&1 | tee -a MAKE_out ; exit $${PIPESTATUS[0]}

preMakefile_simHook:
    @echo ""
```
Then it can be used like this in S_overrides.mk:

```
 preMakefile_simHook : my_prerequisite_goes_here
```

Sorry for not issuing the pull request, I'm using an older version and thought it'd be easier to submit my changes this way :P

**Comment by alexlin0** [comment]
I was able to create some rules in the S_overrides.mk that is only executed before CP is run.  It does involve actually creating a file to tell the makefile don't run me again when I'm cleaning up.

```Makefile
Makefile_sim: my_rule

# Do what you need in my_rule.  Touch my_rule to indicate this rule is up to date.
my_rule:
        echo "HEY THERE"
        touch $@

clean: clean_my_rule

clean_my_rule:
        rm -f my_rule
```

**Comment by dbankieris** [comment]
files are in *italics*
make targets are in **bold**

I figured out why **Makefile_sim** is run as part of **clean** in this case, resulting in *my_rule* being removed, touched, and removed again. 

1\. "make clean" in a SIM directory executes make on *makefile* in that directory
2\. *makefile* includes *${TRICK_HOME}/makefiles/Makefile.sim* and *S_overrides.mk*, both of which have a rule for **clean**
3\. the rule for **clean** now looks like this internally:
```make
clean: clean_my_rule
        @if [ -f Makefile_sim ] ; then $(MAKE) --no-print-directory -f Makefile_sim $@ ; else echo "No Makefile_sim found" ; fi
```
4\. *clean_my_rule* doesn't exist, so make executes its recipe, which removes *my_rule*
5\. now the recipe for **clean** is executed, which invokes "make clean" on *Makefile_sim*
6\. *Makefile_sim* includes *S_overrides.mk*
7\. the rule for **clean** (in this execution of make, which is separate from the original) now looks like this internally:
```make
clean: tidy clean_obj clean_model_io_src clean_lex_yacc_src clean_my_rule
```
8\. From [make's manual](https://www.gnu.org/software/make/manual/html_node/Remaking-Makefiles.html#Remaking-Makefiles): after reading in all makefiles, make will consider each as a goal target and attempt to update it
9\. make therefore first looks for a rule to make **Makefile_sim** (and all the other included files) before **clean**
10. such a rule exists in *S_overrides.mk*:
```make
Makefile_sim: my_rule
```
11\. finding that *my_rule* does not exist (because it was just deleted in step 4), make executes the recipe, which touches *my_rule*, recreating it
12\. now that all of the included makefiles are up-to-date, make proceeds to execute **clean**, which re-removes *my_rule*

**Comment by dbankieris** [comment]
Invoking make on *./Makefile_sim* instead of *Makefile_sim* eliminates steps 10 and 11 (because the rule no longer matches), but does not prevent **clean_my_rule** from being executed twice, since it is included in both *makefile* and *Makefile_sim* and make is invoked on both of those files separately. However, it does get around the issue of doing the expensive part (generating *my_rule*) unnecessarily.

**Comment by alexlin0** [comment]
I'm taking another look at this issue.

I redid the simulation makefile rules for Trick 16.  There are insertion points for both before CP and ICG are run that are not dependent on Makefile_sim.  The clean rule is no longer recursive which should resolve the problem of the rule triggering on clean.  I don't think we have this problem anymore in 16.  We should test it.

I'm debating on whether to put in your suggested fix in 15 because it may be fixed in 16.

**Comment by alexlin0** [comment]
I added your suggested change.  It is the easiest solution to the problem.

**Comment by alexlin0** [comment]
Hold on... we have a rule in the makefile "S_define".  Can you accomplish what you want using this rule rather than creating a new one called preMakefile_simHook

**Comment by ddj116** [comment]
Looks like the S_define rule seems to work in the same way as preMakefile_simHook with no 'make clean' triggering.  I'll migrate our usage to that rule instead. Thanks!
