### ISSUE TITLE
Template from enumerated type does not work

### ISSUE THREAD

**Issue by rachelo** [nasa/trick#139]
It looks like most template issues are fixed except when combined with an enumerated type.  We can get you an example, but not publicly.

**Comment by garyt2** [comment]
Here's an example.  In the .hh file below, there is a line:
%template(der_template_enum) BaseTemplate<my_enum>;

The sim compiles if this line is removed, but then there is no access to the DerClassEnum instance.
With that line included, it does not compile.  Errors out because it tries to redefine "enum my_enum".

If I remove the inheritance from BaseClass at the very top, it works.   The problem is in connecting the DerClassEnum and BaseClass classes.


************************************************************************************************
<<S_define>>
#include "sim_objects/default_trick_sys.sm"
##include "../include/my_classes.hh"
class TestSimObject: public Trick::SimObject
{
 public:
  my_enum       my_enum_instance;
  DummyClass    dummy_class_instance;
  DerClassInt   int_class;
  DerClassEnum  enum_class;
  DerClassDummy dummy_class;

  TestSimObject()
  {
    ("derivative") dummy_class_instance.do_nothing();
  }
 private:
  TestSimObject (const TestSimObject&);
  TestSimObject & operator = (const TestSimObject&);
};
TestSimObject test;
IntegLoop sim_integ_loop (1.0) test;

******************************************************************************************************
<<my_classes.hh>>
class BaseClass
{
 public:
  bool base;
  BaseClass(){};
 private:
  BaseClass (const BaseClass& rhs);
  void operator = (const BaseClass& rhs);
};


template <typename varT>
class BaseTemplate : public BaseClass
{
 public: 
  varT * variable;
  bool   test_access;
  BaseTemplate(){};
 private:
  BaseTemplate (const BaseTemplate& rhs);
  void operator = (const BaseTemplate& rhs);
};

template <typename varT>
class DerTemplate : public BaseTemplate<varT>
{
 public: 
  double der_variable;
  DerTemplate(){};
 private:
  DerTemplate (const DerTemplate& rhs);
  void operator = (const DerTemplate& rhs);
};

class DummyClass
{
 public:
  double dummy_var;
  DummyClass(){};
  void do_nothing(){ dummy_var = 1;};
 private:
  DummyClass (const DummyClass& rhs);
  void operator = (const DummyClass& rhs);
};
 
typedef enum {
  my_val0 = 0,
  my_val1 = 1} my_enum;



#ifdef SWIG
%template(der_template_int) BaseTemplate<int>;
%template(der_template_dummy) BaseTemplate<DummyClass>;
%template(der_template_enum) BaseTemplate<my_enum>;
#endif

class DerClassInt : public DerTemplate<int>
{
 public:
  DerClassInt(){};
 private:
  DerClassInt (const DerClassInt& rhs);
  void operator = (const DerClassInt& rhs);
};

class DerClassDummy : public DerTemplate<DummyClass>
{
 public:
  DerClassDummy(){};
 private:
  DerClassDummy (const DerClassDummy& rhs);
  void operator = (const DerClassDummy& rhs);
};

class DerClassEnum : public DerTemplate<my_enum>
{
 public:
  DerClassEnum(){};
 private:
  DerClassEnum (const DerClassEnum& rhs);
  void operator = (const DerClassEnum& rhs);
};

**Comment by alexlin0** [comment]
I was able to get this to compile by adding a name to the enumeration.  I don't know the details of why this fixes the SWIG code generation bug, but it works. 

```c++
typedef enum MyEnum {
  my_val0 = 0,
  my_val1 = 1
} my_enum;
```
