### ISSUE TITLE
QUESTION: Trick cFS support

### ISSUE THREAD

**Issue by mwebb777** [nasa/trick#1476]
I'm starting a new project and considering using Trick. The project has a requirement to host cFS applications. I saw on the Issues that the cFS interface is no longer supported. Is there a supported way for Trick to interface with cFS?  

Is Trick recommended for new projects? Or should I be looking at another framework like NOS3?

v/r,
Mark
mwebb@jfti.com

**Comment by ezcrues** [comment]
I don't know the status of direct Trick support for cFS.  However, there is a NASA Open Source project called TVS-IO that might help you.  It is designed to help interface between a Trick-based simulation and externally running cFS-based flight software.  Here's the link:  https://github.com/nasa/tvsio

**Comment by excaliburtb** [comment]
NASA JSC does have a TrickCFS capability still maintained and updated for the latest CFS architecture but the path to open-sourcing the project is at the beginning stages. I hope to progress that asap.

The biggest difference between tvsio and TrickCFS is that tvsio handles the message passing and TrickCFS puts the CFS project under the control of a simulated environment (i.e. simulated time rather than wall clock). The latter being useful for synchronization between multiple simulation elements or faster-than-realtime execution. 

just fyi...

**Comment by jmpenn** [comment]
I updated the FAQ:

https://github.com/nasa/trick/blob/master/docs/faq/FAQ.md#core-flight-software-cfs

Thanks!
