### ISSUE TITLE
Bad permissions on files copied to the SIM directory

### ISSUE THREAD

**Issue by danielmatz** [nasa/trick#156]
Trick's `CP` copies files from its own source directory and from the model directories to create `MAKE_out` and populate the `trick` subdirectory of a SIM directory.  It does check the permissions of the files it creates.

All of my users point to the same installation of Trick.  I own the directory where Trick is installed, and I made it read only (even for the user permissions) to prevent me from mucking it up accidentally.

We also build JEOD as a library, and all users point to a common version.  Again, I own the directory, and made it read only so I can't screw it up.

This means that `MAKE_out`, `trick/shortcuts.py`, `trick/m<some hash>.py`, etc., are all read only in the user's SIM directory.  This means that `MAKE_out` contains only the header, and none of the output.  It also means that a subsequent `CP` will fail, since it can't copy the files on top of the existing read only ones.  A `make spotless` is required to clean out the old files.

Can Trick please set permissions on the files it copies/creates?

**Comment by alexlin0** [comment]
Rather than setting permissions, can I suggest that we do something different?  We currently use "cp" to copy files.  I can force the copy with "cp -f".  That seems to work for me for both the trick py files and the JEOD library py files.

As for the MAKE_out file, we have removed the header so there is no copy anymore.  The file is now only touched by the output of make.  This should avoid the permission problem all together.

**Comment by danielmatz** [comment]
That sounds good to me!
