### ISSUE TITLE
Trick ignores simulation build errors

### ISSUE THREAD

**Issue by dandexter** [nasa/trick#1698]
On Linux, I have noticed Trick will ignore errors encountered during the simulation build process and yet you will end up with a compiled and linked simulation executable. This is unacceptable behavior for simulations used for making engineering decisions, analysis, V&V, or interfacing with hardware like emulators. Unless you manually scroll through the console output for the entire sim build process you would not know there were errors and the sim should not be trusted for any verification or validation efforts.

By default, Trick should stop building a simulation when any error is encountered instead ignoring them.

For example, I see many errors like this one (related to issues #1553 and #1556):
```
/usr/include/wchar.h:155:24: error: '__malloc__' attribute takes no arguments
  __attribute_malloc__ __attr_dealloc_free;
                       ^
```

**Comment by alexlin0** [comment]
I am wondering if this is related to an older issue, #1095

**Comment by sharmeye** [comment]
This will require some investigation to determine why these errors are ignored and sim model errors are not.

**Comment by sharmeye** [comment]
This appears not to be an actual error.  This "error" is coming from clang during ICG processing.  This only seems to occur when gcc is defined as the compiler.  It is known that clang and gcc 11 are incompatible because of, among other things, the change in the malloc call in gcc.  Clang is throwing this "error" while parsing the gcc headers.  No object is created, no compilation is occurring, and this behavior doesn't appear when compiler is chosen to be clang at configuration.  We'll continue to investigate but this doesn't seem, at the moment, to be like something you would want to stop a compilation for, b/c no actual compilation error is occurring.  All this does is stop ICG from processing gcc headers?

**Comment by dandexter** [comment]
ICG encountered an error resulting in an interface that is needed by the simulation not getting generated. If the interface is not needed to complete the simulation then it would not have been attempted to generate it. This is clearly a build process error that should not be ignored. Just because there was no compiler error does not mean the build process was error free.

**Comment by sharmeye** [comment]
I think we've answered this question and made the updates to go along with it.  I'm going to close this issue as resolved.
