### ISSUE TITLE
convert_swig's regex for matching qualified template instantiations is incomplete

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#1751]
[This line](https://github.com/nasa/trick/blob/92b0168b7bda0fbcc4ab026e0f1efa4d05fb6b7d/libexec/trick/convert_swig#L718) is looking for template instantiations that are qualified with the scope resolution operator (`::`). The pattern matches instantiations with only a single operator (such as `bar::Foo`) but not those with multiple operators (such as `baz::bar::Foo`). I believe the correct pattern is `^\w*(::\w+)+<`

**Comment by sharmeye** [comment]
Is there a scenario you're encountering that makes this change necessary?  Because we don't support nested namespaces (or classes) so there's not really a situation (we don't think) where this would come into play.  Please provide examples if you are having a problem with how it is currently implemented that this change fixes.

**Comment by dbankieris** [comment]
TrickCAT uses lots of [nested namespaces](https://js-er-code.jsc.nasa.gov/ARGOS/trickcat/-/blob/master/include/trickcat/EL1002.hh?ref_type=heads#L12-14), which didn't cause any problems until f8a079e. #1753 restores enough support for nested namespaces to allow TrickCAT to build within Trick again. Consider it a small step on the path from "we don't support nested namespaces at all" to "we partially support nested namespaces."
