### ISSUE TITLE
Variable Server fails to establish listen port on restart under a specific circumstance.

### ISSUE THREAD

**Issue by excaliburtb** [nasa/Trick#24]
The following conditions will generate a problem with the variable server restarting:
1.) User must specify a port via trick.var_server_set_port(<port_id>) in the input file
2.) Execute simulation and dump a checkpoint on machine A.
3.) ssh to machine B.
4.) Execute simulation and load the checkpoint.

Variable Server will fail with error:
ERROR: Could not establish listen port <port_id> for Variable Server. Aborting.

From this point on, any attempts to connect to the variable server will fail. however, already established connections seem to succeed.

**Comment by alexlin0** [comment]
OK, found it and fixed it.  Commit coming in a minute.

There will still be a problem if you follow this procedure.

1.  User must specify a port via trick.var_server_set_port() in the input file
1.  Execute simulation and dump a checkpoint on machine A.
1.  ssh to machine B.
1.  Remove specifying a port via trick.var_server_set_port() in the input file
1.  Execute simulation and load the checkpoint.

The variable server will move from the random port it was set to in the second execution to the port specified in the checkpoint.  That part works.  The problem is that the sim_control panel will not pick up this change.  You will not be able to start TV from that instance of the sim_control panel.  You can bring up sniffer and connect another sim_control panel to the sim using the variable server port specified in the checkpoint.  Bringing up a new panel is my recommended workaround because getting the sim_control panel to track a moving variable server port was not in it's design.
