### ISSUE TITLE
trick.dr_disable() doesn't do anything :(

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#263]
As the title says, it appears trick.dr_disable() doesn't actually disable logging.

**Comment by alexlin0** [comment]
OK, so we looked at it.  Using this flag does indeed turn off logging.  The log files are created, and header information is written to the file, but actual data is not recorded to the file.  The header information is written so that the groups are ready to go if a dr_enable() call comes around.

If the user does not want to even create the log files, the groups have to removed from the dispatcher, and currently we don't have a method to remove all groups with a single command.

**Comment by ddj116** [comment]
![alright_then](https://cloud.githubusercontent.com/assets/3249339/16503741/030d7ec0-3eda-11e6-9a50-54d4d960298a.jpg)
