### ISSUE TITLE
/usr/lib64/llvm/clang/3.4.2 not found

### ISSUE THREAD

**Issue by bitblit11** [nasa/trick#40]
make fails with:

cp -r /usr/lib64/llvm/clang/3.4.2 lib/clang
cp:  cannot stat `/usr/lib64/llvm/clang/3.4.2': No such file or directory

Centos 6.6
clang/llvm 3.4.2

The source of the error is at:
trick_source/codegen/Interface_Code_Gen/makefile:     cp -r $(CLANG_LIBDIR)/clang/$(LLVM_VERSION) lib/clang

Manually changing CLANG_LIBDIR from "/usr/lib64" to "/usr/lib" fixes the problem.  The CentOS 6 yum repo puts both the 32 bit and 64 bit libraries at /usr/lib/clang/3.4.2.

**Comment by alexlin0** [comment]
The cp line copies the clang/llvm header files to the Interface_Code_Gen directory so that if a pre-compiled Trick is copied to a new machine our ICG utility will have the clang/llvm headers available without the user having to install clang/llvm on the new machine.

Our testing has been using the releases made directly downloaded from the llvm website.  We haven't taken into account disconnects between what llvm-config reports as the instsallation directories and the actual location of files.

**Comment by AMerta** [comment]
Same setup as bitblit11, but I inadvertently reran 'make' after getting the same error. It continued to compile without repeating this error. I did not make any changes as he suggested nor any others.

I could reproduce this behavior with a 'make clean' and then rerun 'make' twice.

From there I needed to 'yum install python-devel' for /usr/include/python2.6/Python.h and 'yum install java-1.8.0-openjdk-devel' for 'javac', but otherwise it finished compiling.
