### ISSUE TITLE
 Should we support -isystem? Cast your vote now!

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#407]
https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

`-isystem` allows you to specify include paths for which all warnings are suppressed. This is useful for silencing warnings in code over which you have no control, such as third-party library headers. Adding this feature would require changes to ICG and `libexec` scripts. Changes are expected to be relatively simple.

**Arguments For**
Trick sims are often riddled with warnings from external code that developers cannot address themselves. These "nuisance warnings" obscure the warnings developers actually _can_ fix, which results in missed opportunities to correct issues early or, worse, habitual dismissal of _all_ warnings. Support of this feature in Trick would allow developers to hide warnings from other projects (JEOD, GUNNS, Pong, etc) in addition to non-Trick-related third-party library headers when building their sims. Developers could then more easily address their code's warnings, which would result in higher-quality sims.

**Arguments Against**
`-isystem` is not a well-known option, and there have been no requests to support it. It may not be worth the effort to add it. Furthermore, it could be abused to silence warnings in _all_ code, which is even worse than seeing and ignoring them.

**Comment by gitschooldude** [comment]
I support the end goal, and if `-isystem` is the way to get there, then I support that too.  

Like and subscribe,
Gitschooldude

**Comment by lordmundi** [comment]
Support!

FG

**Comment by alexlin0** [comment]
Against.

I can't  get the -isystem flag to work in SIM_Ball++_L1.  Here is my methodoloy

1.  Add this code that creates warnings in the Ball class in Ball.hh

```c++
   int dummy() {
       int ii ;
       unsigned int jj ;
       if ( jj < 0 ) {
       }
       if ( jj < ii ) {
       }
   }
```

2. Build SIM_Ball++_L1 sim to completion with warnings.
3. Edit S_overrides.mk changing -I./models to -isystem./models
4. Touch models/Ball.cpp forcing just the one file to recompile
5. <code>make</code> and the warnings persist.

I could note get any permutation of -isystem to suppress the warnings because in this sim it turns out you only need a the <code>-I./models</code> for ICG.  If you change step 3 to remove TRICK_CFLAGS and TRICK_CXXFLAGS entirely, the <code>make</code> in step 5 still works.

**Comment by jmpenn** [comment]
Mildly against, but if it isn’t feasable …

John

**Comment by alexlin0** [comment]
I don't see how my test is different than what you are trying to do.  For my test I am pretending that I no longer have control over the source code in the ball model directory.  I want to suppress warnings in the ball directory but can't because it includes source in the same directory.

**Comment by alexlin0** [comment]
What if you change -I to -isystem in the S_overrides.mk.  You can use multiple lines to change multiple strings of text.

```make
$(MODEL_OBJECTS): TRICK_CXXFLAGS := $(subst -I./models,-isystem./models, $(TRICK_CXXFLAGS))
```
This doesn't require a Trick change.

**Comment by dbankieris** [comment]
The difference is between whose source code you're compiling.

1. Your Source
When compiling one of your own source files that `#include`s a third-party header, warnings from that header can be suppressed via `-isystem`. This is the stated purpose of that option.

2. Third-Party Source
When compiling a third-party source file, `-isystem` may be ineffective at suppressing warnings from its `#include`d headers due to the issue noted in my previous comment. Moreover, warnings from the source file itself cannot be suppressed with `-isystem` at all. This is not what `-isystem` is meant for. Suppression of these warnings is a related but separate discussion.

Consider this [simple example sim](https://github.com/dbankieris/SIM_isystem). It consists of a third-party header `Warning.hh` which is included by third-party `Warning.cpp` and local `Foo.cpp`. When built, the same warning is reported from _seven_ different source files: `Foo.cpp`, `Warning.cpp`, `Warning_py.cpp`, `S_source.cpp`, `S_source_py.cpp` ,`io_S_source.cpp`, and `top.cpp`. That alone is enough to make me want to ignore all of Trick's output.

Five of those redundant warnings can be suppressed via `-isystem`. Your `subst`-based solution is clever, but  we need a target-specific variable for more than just `MODEL_OBECTS`. We also need to affect `S_OBJECTS`, `IO_OBJECTS`, and `SWIG_OBJECTS`. And we need to change both `TRICK_CFLAGS` and `TRICK_CXXFLAGS`. This approach is illustrated in the [subst branch](https://github.com/dbankieris/SIM_isystem/blob/subst/S_overrides.mk). It works, but it relies on Trick makefile variable names (which we recently decided were not part of Trick's public interface) and advanced makefile knowledge.

Contrast that with the [isystem branch](https://github.com/dbankieris/SIM_isystem/blob/isystem/S_overrides.mk). The only requirement here is that they learn a new flag. Which would you rather have users calling us for help with?

The two files for which we cannot suppress warnings via `-isystem` are:
- `Warning.cpp`
Because it shares its directory with `Warning.hh`, `-isystem` is not the appropriate tool. There is a solution, but it's part of that related but separate discussion I mentioned ealier.
- `Warning_py.cpp`
Because its `#include` uses an absolute path. If we changed the `.i` files to use relative `#include`s, `-isystem` could suppress this warning as well.

**Comment by alexlin0** [comment]
I'd rather not have to help users with either of your options.  I know that this will not be a hard feature to implement.  But this feature has a smell to me, it's for a single project using rarely used compiler flags to support an approach I don't agree with.  I don't like adding things into Trick like this.  But it sounds like you're determined to get this in.  So go ahead and do it for now.  You'll need all of the options <code>-iquote</code> and <code>-idirafter</code> as well.  My request when we close this issue is to add a new issue with dated 6 months from now to follow up with the one group to see if they are still using this.

**Comment by dbankieris** [comment]
Note to myself: It turns out `-isystem` also excludes headers from ICG as `HeaderSearchDirs::isPathInUserDir` returns `false` for any files in a system path.
