### ISSUE TITLE
MonteVarFile's number of columns equals number of times the files is opened

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#432]
Recently our group ran into the following error only on particular machines when running a specific monte-carlo run:

```
DIAGNOSTIC: Trick:MonteVarFile the input file "path/to/our/file.txt" failed to open
```
After digging into it a bit, I found that the reason the file failed to open was because we had hit the maximum number of open files for that process on that machine (See #431), in this case the default number is 1024.  We can of course configure our machines to increase this limit, but that number seemed high to me so I started looking a bit closer at `Trick::MonteVarFile::set_file_name` which is where these files are opened.

I noticed that each `MonteVarFile` we create in our input file was resulting in a calls to `Trick::MonteVarFile::set_file_name` which in turn opens the same file many times.  More specifically, the file is opened once for each column of data that the sim is configured to use, at input processor time, and *leaves the file handles open for the instance to use later*.  For example we have one such file that has 190 columns of data, here's what our input file configuration looks like:

```python
var1   = trick.MonteVarFile("simobj.myValue[0]", "Modified_data/monte_carlo/my_mcvar_file.txt", 1)
trick_mc.mc.add_variable(var1)
var2   = trick.MonteVarFile("simobj.myValue[1]", "Modified_data/monte_carlo/my_mcvar_file.txt", 2)
trick_mc.mc.add_variable(var2)
...
var190 = trick.MonteVarFile("simobj.myValue[190]", "Modified_data/monte_carlo/my_mcvar_file.txt", 190)
trick_mc.mc.add_variable(var190)
```

If this were our only variable, a single monte carlo input data file results in 190 open file handles to the same file at input-processor time.  No wonder we hit our 1024 limit so easily!

This design seems like it could be refactored such that the Trick monte-carlo framework isn't holding on to a file handle per column of the file.  A simple fix might be to change when the file gets opened, so that the file is opened, read, and closed all in one shot.  Or perhaps the architecture could change such that the user only has to instantiate one `MonteVarFile` per file (instead of per-column per-file).

**Comment by CTLaChance** [comment]
There are two solutions that have been discussed regarding this issue.

### Tell and Seek
Using the [tellg](http://en.cppreference.com/w/cpp/io/basic_istream/tellg) and [seekg](http://en.cppreference.com/w/cpp/io/basic_istream/seekg) functions, it is possible to store and restore the position indicator for the current input stream. The process would be to open the data file, read the values we need for the line we are on, and then close the data file again. The next time we need a value from the file, we simply restore the position we were at and read once more.

This solves the concurrent open file handles issue and has the benefit of being compatible with all current input file declarations. The downside is that you still have 1000 different file handles all pointing to the same file. 

###  MonteDataFile
By creating a separate class called MonteDataFile, we can instantiate a single file handle per data file. This object would read a line from the data file, tokenize it, and then store each tokenized value into a vector<std::string>. Now you can easily create multiple MonteVarFile variables that want different or even the same column of information from a specific file. 

The upside is that it cleanly solves the concurrent  open file issue and it's easy to understand. The downside is that in order to make use of this functionality you would need to modify your input file to something like the following:

```python
# Open a file by data file for use with Monte Carlo file variables.
DataFile0 = trick.MonteDataFile("path_to_data_file_0")
DataFile1 = trick.MonteDataFile("path_to_data_file_1")
DataFile2 = trick.MonteDataFile("path_to_data_file_2")

# Create MonteVarFile that pull values from different files.
var0 = trick.MonteVarFile("variable_name_0", DataFile0, column_number, "unit")
var1 = trick.MonteVarFile("variable_name_1", DataFile0, column_number, "unit")
var2 = trick.MonteVarFile("variable_name_3", DataFile1, column_number, "unit")
var3 = trick.MonteVarFile("variable_name_5", DataFile2, column_number, "unit")

# Add variables to monte carlo.
trick_mc.mc.add_variable(var0)
trick_mc.mc.add_variable(var1)
trick_mc.mc.add_variable(var2)
trick_mc.mc.add_variable(var3)
```

**Comment by CTLaChance** [comment]
The second solution also has the added benefit of being able to more easily solve issue #459.

**Comment by dbankieris** [comment]
A further disadvantage of the second solution is that it requires additional logic in the master that breaks polymorphism. Currently, the master only knows about `MonteVar`s. With the proposed `MonteDataFile` solution, someone has to tell each `MonteDataFile` when to read the next line of its file. So now the master has to treat `MonteVarFile`s differently than all other `MonteVar`s. Not good.

Furthermore, it subtly changes the contract of `MonteVarFile::get_next_value`. Currently, calling `get_next_value` always returns the next value from the file. Under the proposed change, it would return the same value until `MonteDataFile` read the next line. A subclass overriding a function in the superclass should not change the contract.

Finally, the tell and seek solution actually has better file handle management, in my opinion. I think it is prudent to close a file when you aren't using it. Tell and seek only ever has a single file handle open, whereas `MonteDataFile` maintains an open file handle for every `MonteDataFile`, so the user could still hit the limit.

For these reasons, I prefer the tell and seek solution despite its higher complexity. As you noted, it's also transparent to the user, which is valuable.
