### ISSUE TITLE
Unable to configure Trick with Java 9

### ISSUE THREAD

**Issue by mpfritz** [nasa/trick#486]
There appears to be a bug in the "configure" script when Java 9 is the default Java version on the machine. When performing a "java -version" or "java -version" command via command line, it returns:

java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

AND

java 9

When running the "configure" script, an error appears stating it cannot locate a version of java newer or equal to version 1.8.

Thad Fleming tracked this bug down to the way the "configure" script looks at the version number of Java. It makes an assumption that the version number is of the form 1.#. However, for Java 9, this assumption is no longer true. 

Need an update to the "configure" script that will allow for compilation with Java 9.

**Comment by iamthad** [comment]
The format of Java's version strings has changed as described in [JEP 223](http://openjdk.java.net/jeps/223). Fortunately, this only affects Java version 9 and up. So it will work fine to compare 9 to 1.8 and have that return true.

I think this can be fixed by making the second portion of the version string regex optional. I'll take a crack at that later today.

**Comment by alexlin0** [comment]
Solved it the same way you were going to try.  Eventually this check would have failed at "1.10" if java continued on with it's old numbering scheme.
