### ISSUE TITLE
Is Trick ICG missing some uses of TRICK_ICG

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#608]
Test to see if Trick is catching the use of TRICK_ICG in this statement
```
#if !defined(SWIG) && !defined(TRICK_ICG)
```
We may be missing this case, and only on the Mac.

**Comment by excaliburtb** [comment]
Probably not getting the following syntax still:
```
#if  !defined(SWIG) && !defined(TRICK_ICG)
      CheckpointHelper_alias::UnsafeChkptVector<BODY_DATA *> workingBodies; /* ** list of bodies to be processed by parallel tasks */
#endif
```

**Comment by dbankieris** [comment]
[`FindTrickICG::If`](https://github.com/nasa/trick/blob/334f8859da7e11d316d00c433e7bc22c7619881a/trick_source/codegen/Interface_Code_Gen/FindTrickICG.cpp#L38) is called whenever clang encounters a preprocessor IF directive, which seems to include at least `#if`, `#ifdef`, and `#ifndef`. If the directive includes `TRICK_ICG`, ICG marks all files in the current include chain as being tainted, meaning we must use `offsetof` in the `init_attr` functions to get address information for the `ATTRIBUTES` arrays. If multiple files include the same tainted file, only the files in the include chain when the tainted file is first encountered will be properly marked. This is because the header guard in the tainted file prevents clang from seeing `TRICK_ICG` in subsequent includes of that file. While [this page](https://gcc.gnu.org/onlinedocs/cpp/Ifdef.html) says that the preprocessor still parses text within a failed conditional, the page on [once-only headers](https://gcc.gnu.org/onlinedocs/cpp/Once-Only-Headers.html#Once-Only-Headers) reveals that the preprocessor not does rescan headers with guards if they've already been processed. In any case, `FindTrickICG::If` is not called for subsequent includes of a tainted header.

In the example below, `Bar.hh` and `Baz.hh` both include the tainted `Foo.hh`. While `io_Bar.cpp` calls `offsetof` to correct the offsets in its `ATTRIBUTES` array, `io_Baz.cpp` does not, and its offsets remain wrong.

Foo.hh
```c++
// @trick_parse{everything}
#ifndef FOO_HH
#define FOO_HH

class Foo {
    #ifndef TRICK_ICG
    int i;
    int j;
    int k;
    #endif
};

#endif
```

Bar.hh
```c++
// @trick_parse{everything}
#include "Foo.hh"

class Bar {
    public:
    Foo foo;
    int i;
};
```

Baz.hh
```c++
// @trick_parse{everything}
#include "Foo.hh"

class Baz {
    public:
    Foo foo;
    int i;
};
```

io_Bar.cpp
```c++
void init_attrBar() {

    static int initialized ;
    if (initialized) {
        return;
    }   
    initialized = 1;

    attrBar[0].offset = offsetof(Bar, foo) ;
    trick_MM->add_attr_info(std::string(attrBar[0].type_name) , &attrBar[0], __FILE__ , __LINE__ ) ; 
    attrBar[1].offset = offsetof(Bar, i) ;
}
```

io_Baz.pp
```c++
void init_attrBaz() {

    static int initialized ;
    if (initialized) {
        return;
    }   
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrBaz[0].type_name) , &attrBaz[0], __FILE__ , __LINE__ ) ;
}
```
