### ISSUE TITLE
QUESTION: Trying to Install Trick on Windows 10!

### ISSUE THREAD

**Issue by parksung123** [nasa/trick#643]
I installed Ubuntu following the instructions given and ran Bash Shell. However, this step:

Open a bash shell and install the following packages.with:

sudo apt install bison curl flex g++ libx11-dev libxml2-dev \
 libxt-dev libmotif-common libmotif-dev make python2.7-dev \
 swig zlib1g-dev llvm llvm-dev clang libclang-dev libudunits2-dev 

does not seem to work. This is what happens:

![image](https://user-images.githubusercontent.com/33106112/42092533-3c256db4-7be4-11e8-95e2-9a9b22686b9d.png)

Then I tried the next step, Install Java JDK 8 through the ppa repository, which seemed to work. Please help!!

**Comment by alexlin0** [comment]
It's been a while since we've updated the Windows 10 instructions.  I currently have Windows 10 version 1709 OS Build 16299.15 on a machine and encountered the same error you did when trying to use Ubuntu 18.04.  I've updated the [instructions to install Trick under Windows 10 version 1709]https://github.com/nasa/trick/wiki/Install-Guide#windows-10-version-1709-os-build-16299-fall-creators-update()
