### ISSUE TITLE
racecondition in posix platform

### ISSUE THREAD

**Issue by RootUp** [nasa/trick#656]
Team, 

File such as : 
trick/trick_source/data_products/DPX/APPS/FXPLOT/fxplot.cpp:205
trick/trick_source/data_products/DPX/APPS/FXPLOT/page_view_node.cpp:183

```
    if (!access("/tmp", W_OK)) {
        strncpy(tmp_file, "/tmp/fxplot_XXXXXX", sizeof(tmp_file));
    } else if (!access("/var/tmp", W_OK)) {
    	strncpy(tmp_file, "/var/tmp/fxplot_XXXXXX", sizeof(tmp_file));
    } else {
        post_dialog( toplevel, XmDIALOG_ERROR,
        	         "Unable to access /tmp or /var/tmp, where a temporary\n"
        	         "Postscript file (that represents your print out) needs\n"
        	         "to be generated. Please check your file permissions.\n");
        return;
}
```

I believe this indicates a security flaw, If an attacker can change anything along the path between the call `access()` and the files actually used, attacker may exploit the race condition or a time-of-check, time-of-use race condition, request team to please have a look and validate.

Reference: https://linux.die.net/man/2/access

**Comment by iamthad** [comment]
It looks like @RootUp here is creating issues like this in an automated or semi-automated fashion on a variety of projects. Here are some examples: [1] [2] [3] [4] [5]

The issues seem to cover any use of access(2).

If I'm reading the man page for access(2) correctly, it's a security issue for setuid / setgid programs. I don't think running fxplot as setuid / setgid is the norm. I don't think this particular use is a security issue, since it's just checking whether these temporary directories are writable.

[1]: https://github.com/rhboot/fwupdate/issues/122
[2]: https://github.com/github/glb-director/issues/30
[3]: https://github.com/nasa/icarous/issues/48
[4]: https://github.com/dell/libsmbios/issues/62
[5]: https://github.com/nodejs/node/issues/22056

**Comment by alexlin0** [comment]
I agree with you, @iamthad, the way we are using access is not a security risk. Before I close this as a not an issue, I'll let others have a chance to comment.

**Comment by jmpenn** [comment]
@iamthad, I also agree with you. Thanks for the research, and for exposing this "issue" for what it is.
