### ISSUE TITLE
SIM_ball_L3 multistep integration not working

### ISSUE THREAD

**Issue by keithvetter** [nasa/trick#725]
SIM_ball_L3 is not taking all the intermediate integration steps when using an RK4.  I believe there is a general problem with integrating over multiple sim objects using a multi-step integrator.  

In Trick07, there were separate integrators passed as arguments to the integration jobs, so the intermediate step was independent for each sim object.  I am guessing that in Trick17 there is a single integrator class shared among the sim objects and that ball_state_integ() called for both _ball_ and _ball1_ is incrementing the same intermediate step.

Currently, the SIM_ball_L3 S_define has this line:
```
("integration") ball_state_integ( &state ) ;
```

I tried adding _trick_ret_ but that did not work:
```
("integration") trick_ret = ball_state_integ( &state ) ;
```

**Comment by keithvetter** [comment]
I attached a comparison plot of ball1's position between Trick07 and Trick17 using RK_4.  The plot shows that there is a wild difference between the two responses.

![ball-L3-comparison-plot](https://user-images.githubusercontent.com/1434444/56301278-1c578180-60fd-11e9-807a-48de52162d16.jpg)

**Comment by jmpenn** [comment]
SIM_ball_L3 demonstrates several problems with Trick numerical integration
which are being addressed by the following issues.

* #936  - Trick Numeric Integration Re-design
* #1056 - Add new stand alone numerical integration library SAIntegrator #1056

As for getting SIM_ball_L3 to work, the ball states have been combined into an
ensemble state, containing eight, rather than four elements. Notice that the
derivative jobs are run for each instance of BallSimObject. But states are
integrated as an ensemble. Also the dynamic-event job controls the ensemble state.
Also replaced Runga Kutta Fehlberg 45 with Runge-Kutta-4, because what has long 
been called Runge-Kutta Fehlberg in Trick does not actually implement Runge-Kutta 
-Fehlberg.
