### ISSUE TITLE
Trick inappropriately disowns memory allocated in Python

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#903]
Foo.hh
```c++
// @trick_parse{everything}
class Foo {
    public:
    int i;
};
```

S_define
```c++
#include "sim_objects/default_trick_sys.sm"
##include "Foo.hh"
```

input.py
```python
f = trick.Foo()
print f.thisown
f.i = 1 
print f.thisown
```

Output
```
True
False
```

Setting `f.i` calls `_wrap_Foo_i_set`, which calls `SWIG_ConvertPtr`, which is macro'd to `SWIG_Python_ConvertPtr`, which is macro'd to `SWIG_Python_ConvertPtrAndOwn`, which has the following block:

```c++
    if (flags & SWIG_POINTER_DISOWN) {
      soobj->own = 0; 
    }
```

Many of our calls to `SWIG_ConvertPtr` pass `SWIG_POINTER_DISOWN`.

**Comment by DavidHammen** [comment]
I can confirm that this happens in multiple places. JEOD recently received a user complaint regarding JEOD's report of unreleased memory. Allocating a JEOD reference frame in the python input file and doing nothing else with it resulted in no complaints from JEOD. But touching it in any way (e.g., frame.state.trans.position[0]=0.0) resulted in the call to `SWIG_Python_ConvertPtrAndOwn` referenced above, resulting in JEOD complained about a leak because the ref frame was no longer deleted.

**Comment by excaliburtb** [comment]
this came up again in recent sim updates. bumping this issue

**Comment by sharmeye** [comment]
@excaliburtb we're working a solution that we'd like you to try.  We believe our solution solves the problem for all but one specific case, for which we will include the following in the documentation:

If a pointer is declared in a sim object but not allocated, and the allocation occurs in the input file for that pointer, then the Trick Memory Manager needs to be used to allocate the memory for that pointer.  Otherwise, in this case, neither Python nor the Memory Manager will own the memory.
